server:
  port: 9000
spring:
  datasource:
    name: test
    url: jdbc:mysql://47.98.211.153:3306/invitations?characterEncoding=utf8
    username: root
    password: Yuzj2018$
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.love.model.pojo  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.love.mapper: debug


wexin:
  url: https://api.weixin.qq.com/sns/jscode2session
  appid :  wx1c9835e404cc3d69
  secret : 1a0d1181ff2295a1363fe0260ce4b789

